version: '2'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    container_name: "workspace"
    build:
      context: ./workspace/
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - LNMP_PHP72_VERSION=${PHP72_VERSION}
        - UBUNTU_SOURCE=${UBUNTU_SOURCE}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
        - INSTALL_SUPERVISOR=${WORKSPACE_INSTALL_SUPERVISOR}
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_BROWSERSYNC_HOST_PORT}:3000"
      - "${WORKSPACE_BROWSERSYNC_UI_HOST_PORT}:3001"
      - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT}:8080"
      - "${WORKSPACE_VUE_CLI_UI_HOST_PORT}:8000"
      - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT}:4200"
    networks:
      - frontend
      - backend
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php-worker/supervisord.d:/etc/supervisord.d

  php-fpm72:
    container_name: "espier-php"
    build:
      context: php72/
      args:
        - LNMP_PHP72_VERSION=${PHP72_VERSION}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php72/php-dev.ini:/usr/local/etc/php/php.ini:cached
      - ./php72/php-fpm.conf:/usr/local/etc/php-fpm.conf:cached
      - ./php72/php-fpm.d:/usr/local/etc/php-fpm.d:cached
      - ../logs/php-fpm72:/var/log/php-fpm:cached
    restart: always
    command: php-fpm

  openresty:
    container_name: "espier-openresty"
    build:
      context: openresty/
      args:
        - LNMP_OPENRESTY_VERSION=${OPENRESTY_VERSION}
    # privileged: true
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${VARNISH_BACKEND_PORT}:81"
    networks:
      - frontend
      - backend
    links:
      - php-fpm72
      - php-fpm74
    depends_on:
      - php-fpm72
      - php-fpm74
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      - ./openresty/conf.d:/etc/nginx/conf.d:cached
      - ../logs/openresty:/usr/local/openresty/nginx/logs:cached
    restart: always
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #       systemctl start snapd

  ### MySQL ################################################
  mysql:
    container_name: "espier-mysql"
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - frontend
      - backend
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:rw
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ../logs/mysql:/var/lib/mysql-logs:cached
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    restart: always
    command: "--character-set-server=utf8"

  ### Redis ################################################
  redis:
    container_name: "espier-redis"
    build: ./redis
    volumes:
      - ./redis/redis.conf:/etc/redis.conf:rw
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    command: "/etc/redis.conf"
    restart: always

  ### PHP Worker ############################################
  php-worker:
    build:
      context: ./php-worker
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - LNMP_PHP72_VERSION=${PHP72_VERSION}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - PUID=${PHP_WORKER_PUID}
        - PGID=${PHP_WORKER_PGID}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend

  php-fpm74:
    container_name: "salesperson-php"
    build:
      context: php74/
      args:
        - LNMP_PHP74_VERSION=${PHP74_VERSION}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
        - INSTALL_AMQP=${PHP_WORKER_INSTALL_AMQP}
    ports:
      - "9001:9000"
    networks:
      - backend
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php74/php-dev.ini:/usr/local/etc/php/php.ini:cached
      - ./php74/php-fpm.conf:/usr/local/etc/php-fpm.conf:cached
      - ./php74/php-fpm.d:/usr/local/etc/php-fpm.d:cached
      - ../logs/php-fpm74:/var/log/php-fpm:cached
    restart: always
    command: php-fpm

    ### RabbitMQ #############################################
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    hostname: mydock-rabbitmq
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
    depends_on:
      - php-fpm74
    networks:
      - backend